#!/bin/bash

echo "Mountebank4proxy @ Oney is starting"

CONFIG_FILE_NAME="imposters.json"
ONEY_CONFIG_DIR=/mountebank/oney
MOUNTEBANK_CONFIG_DIR=/mountebank/config
MOUNTEBANK_ONEY_IMPOSTER_JSON="$ONEY_CONFIG_DIR/$CONFIG_FILE_NAME"
MOUNTEBANK_IMPOSTER_JSON="$MOUNTEBANK_CONFIG_DIR/$CONFIG_FILE_NAME"

echo "Replacing var in config $MOUNTEBANK_IMPOSTER_JSON"
cp $MOUNTEBANK_ONEY_IMPOSTER_JSON $MOUNTEBANK_IMPOSTER_JSON
chmod +x ${MOUNTEBANK_IMPOSTER_JSON}
sed -i -e "s|MOUNTEBANK_PROXY_TO_TO_REPLACE|${MOUNTEBANK_PROXY_TO}|g" $MOUNTEBANK_IMPOSTER_JSON
chmod -x ${MOUNTEBANK_IMPOSTER_JSON}
# Start process
echo "Starting Mountebank with $MOUNTEBANK_IMPOSTER_JSON"
mb --configfile $MOUNTEBANK_IMPOSTER_JSON